apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-controller-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-controller
  template:
    metadata:
      labels:
        app: kube-controller
    spec:
      containers:
        - name: kube-controller-container
          image: kube-controller:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8000